name: hr_plus
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.2+8

environment:
  sdk: ^3.8.1


dependencies:
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.5.0
  circular_gradient_spinner: ^0.0.3
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7

  flutter:
    sdk: flutter
  flutter_alice: ^2.0.1
  flutter_bloc: ^9.1.1
  flutter_lints: ^6.0.0
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.14.0
  gradient_circular_progress_indicator: ^0.0.4
  hive_flutter: ^1.1.0
  http: ^1.6.0
  icons_launcher: ^3.0.1
  image_picker: ^1.1.2
  injectable: ^2.5.0
  internet_connection_checker: ^3.0.1
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.3.0
  mask_text_input_formatter: ^2.9.0
  numberpicker: ^2.1.2
  pinput: ^5.0.1
  retrofit: ^4.9.1
  shimmer: ^3.0.0
  smart_auth: ^3.2.0
  smooth_page_indicator: ^1.2.1
  flutter_pdfview: ^1.4.3

  url_launcher: ^6.3.2
  sms_autofill: ^2.4.1
  syncfusion_flutter_datepicker: ^32.1.21




dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  retrofit_generator: ^10.2.0




flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/translations/
    - assets/translations/uz-UZ.json

icons_launcher:
  image_path: "assets/icons/app_icon.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter_assets_generator:
  output_dir: /core/resources
  auto_detection: true
  named_with_parent: false
  output_filename: assets
  class_name: Assets
  filename_split_pattern: "[-_]"
  path_ignore:
    - assets/translations/
    - assets/images/
    - assets/fonts/